### ISSUE TITLE
KPanic on 6.72

### ISSUE THREAD

**Issue by cspencer49519** [ethylamine/PS4-RDR-2-Menu-Base#2]
Hello, I've been trying to get this payload working all day. I've tried incorporating it with my working base, and just compiling from source. I can't get it to launch.

I have tried the payload on a slim/9.00 and a pro/6.72, both just lcok and reset the console.

I'm using the latest payload sdk with your pr for CEIL

I've tried with hen 2.13b/binloader.

**Comment by ethylamine** [comment]
Hello,
I made some changes to the repo recently so that the payload can be PIE (basically not depend on the static addresses 0x9262000000000000 and 0x9263000000000000).

Are you using that version or the older one before the PIE changes?

Are you loading more than one payload besides HEN when you start the game?

By binloader I assume you mean you're using AlAzif's DNS payload host?

Try running a standalone HEN payload first, then the menu payload, then start the game.

If it freezes your entire console then something else is going on. During my testing, at most it just crashed the game.

You might have to provide kernel logs to troubleshoot further.

**Comment by cspencer49519** [comment]
I'm using the latest commit. 
I'm not loading anything except HEN.
I'm sending the payload via netcat, using the standard binloader for 6.72 at port 9021.
It kills my console when I start the game.
Here's the kernel log:

https://pastebin.com/saJB7GtV

**Comment by ethylamine** [comment]
To be honest, that log doesn't help much. 
What it does reveal is that some code ran in kernel mode is causing a fault for whatever reason.
The `patch_ptrace` function is basically the only code I added that is ran in kernel mode (besides AlAzif's from the payload sdk).
Maybe try commenting out that 6.72 ptrace patch and see if anything changes.
I only own a 5.05 so unfortunately I can't reproduce your issue.
One of my testers confirmed it worked on 9.00 as well.
You can also start adding some print statements to see where in the code the payload may be crashing (I believe the function `printf_debug` from the payload sdk will print to kernel log).
The already compiled payload in the repo also doesn't work for you right?

**Comment by cspencer49519** [comment]
The included bin and the compiled one both produce the same results. These are the ptrace and other patches for 6.72 that work on my other gta 5 payload:

    // 6.70, 6.71, and 6.72
	// patch memcpy first
	*(uint8_t *)(ptrKernel + 0x003C15BD) = 0xEB;

    // patch ptrace
    *(uint8_t *)(ptrKernel + 0x10F879) = 0xEB;
	  memcpy((void *)(ptrKernel + 0x10FD22), "\xE9\xE2\x02\x00\x00", 5);

    // Disable process aslr
    *(uint8_t *)(ptrKernel + 0x3CECE1) = 0xEB;

Also, shouldn't this code reference the payload address:

#define HookBytes 0x48, 0x8D, 0x15, 0xDE, 0xCD, 0x57, 0x04 // 1.00 version
// 1.29 patch = 48 8D 15 48 7C 43 05

/*
lea rdx, [rip+0x457CDDE]
1.29 = lea rdx, [rip+0x5437C48]
*/

I see the 1.29 patch is commented out, do the hookbytes need to be changed?

**Comment by cspencer49519** [comment]
Same behavior with ptrace_patch commented. Also I'm testing on 9.00 and 6.72, but I don't have UART on my 9.00 console, same behavior there, though.

**Comment by ethylamine** [comment]
In `main`, the actual 1.29 bytes get written to memory once it detects the 1.29 version so I never bothered to change that snippet. Yes, that code should point to PayloadAddress (and it does as shown below). I could change it later but it isn't necessary at the moment.
`if (GameVersion == 0x81) //new for 1.29
`{

	u8 hookASM[] = { 0x48, 0x8D, 0x15, 0x48, 0x7C, 0x43, 0x05 };

	procWriteBytes(gamePID, HookAddress, hookASM, sizeof(hookASM));
`}`
As for the ptrace patch, I took it from mira [seen here](https://github.com/kiwidoggie/mira-project/blob/develop/kernel/src/Boot/Patches/Patches672.cpp#L126).
Feel free to change the patch and see if it resolves your crash. If so, you can PR and I'll merge it or I can do it myself once you confirm it works.

Also, I noticed the payload sdk also uses a different ASLR patch than you do.
Try commenting out or removing the call to `disable_aslr`. 
You would have to patch it yourself if that is the issue.

**Comment by cspencer49519** [comment]
In gta.h, payload address is set as follows:

#define PayloadAddress (void*)0x75FCA80

Then there's this in main.c:

	if (GameVersion == 0x81) //new for 1.29
	{
		u8 hookASM[] = { 0x48, 0x8D, 0x15, 0x48, 0x7C, 0x43, 0x05 };
		procWriteBytes(gamePID, HookAddress, hookASM, sizeof(hookASM));
	}

Shouldn't this be:
	if (GameVersion == 0x81) //new for 1.29
	{
		u8 hookASM[] = { 0x48, 0x8D, 0x15, 0x80, 0xCA, 0x5F, 0x07 };
		procWriteBytes(gamePID, HookAddress, hookASM, sizeof(hookASM));
	}

To reflect the payload address?

**Comment by ethylamine** [comment]
Oh yeah that, I tried it that way initially and it would crash the game. If you set it to about 6 or 7 bytes before the payload address, it would work fine. Probably some alignment thing going on not sure.
I confirmed that a certain other menu payload does it the same way.
Feel free to try whatever you think could fix it on your end.

**Comment by cspencer49519** [comment]
I must be missing something, you said six or seven bytes before the payload, you have the payload address set to 0x75FCA80, and your hookaASM represents the address 0x05437C48, that's a difference of 21C4E38 bytes? I've been creating payloads for GTA V for a couple years now, I've never seen it setup like this. Maybe I'm missing something, but I don't understand how this works.

**Comment by ethylamine** [comment]
I wrote what the asm will look like for 1.29 in gta.h
hook asm represents the _current instruction address + 0x5437C48_
`lea rdx, [rip+0x5437C48]`
0x21C4E31 + 0x5437C48 = 0x75FCA79
0x75FCA80 - 0x75FCA79 = 7
0x21C4E31 = HookAddress

**Comment by cspencer49519** [comment]
I see, that's what I'm missing, thank you for explaining. I have replaced your patch ptrace with the standard kernelPayload I use on my gta v menu, I get the notification that the menu has loaded, then I either sit at the loading screen perpetually, or the scene cuts to black, the light on the controller goes red, like you're in gameplay, but the screen just stays black. I get a 
Kernel Fault 9 in the log.

**Comment by ethylamine** [comment]
Not sure what your issue could be without some debugging or looking at your source.
As I mentioned earlier try using `printf_debug` to pinpoint where in the code the payload could be crashing.

**Comment by cspencer49519** [comment]
OK so I did some further testing, it's getting stuck at initLibs/resolveLibs, the test looks like it's looking for malloc to resolve, and it looks like that's not happening.

**Comment by cspencer49519** [comment]
Here is the code I'm working with. It's not a syscall issue, as I'm using syscall to log to console and that is working. I'm kind of stumped. Maybe you can see something obvious I've missed.

https://mega.nz/file/GZ5gTYyJ#1EuanVb_A9WDBEdGuCtE4hzL6HbYmw-t3S8OH9V_wok

**Comment by ethylamine** [comment]
You changed a good amount of the code. I'm not going to debug code I didn't write sorry.
I did notice in your kernel payload you have a ton of unnecessary patches. The only ones you need for this payload are ASLR and ptrace. Seems like they are patches from ps4debug.
You also don't need to manually resolve the sysutil library as the payload sdk takes care of that for you with `initSysUtil`.
A lot of stuff you are doing is already taken care of or done by the payload sdk.

**Comment by cspencer49519** [comment]
Oh, OK. If you would prefer I can switch back to your code that completely crashes my console as soon as the bin is sent? Would be happy to if you can tell me what's wrong with it, because it doesn't work. I'm simply trying to get this working. I have talked to three others besides myself, none of us have gotten this to work. We are all either on 6.72 or 9.00. By subbing in code that works for other mods, I was able to at least get it loading, just trying to get it working.

Also, I only changed the portion of the code that patches the kernel, and changed it to use the hookBytes from gta.h instead of passing them in main. All the other code is exactly the same.

The game is executing and loading fine, it now crashes when I attempt to initiate the menu (R1+R3).

**Comment by ethylamine** [comment]
It works on 9.00 according to another tester with goldHEN and the payload loaded via AlAzif's DNS host.
6.72 is buggy and refuses to work so I'm going to strip out the code for that.
I have no clue what your issue could be without kernel logs.

**Comment by cspencer49519** [comment]
The latest commit seems to fix the issue as long as I compile with gcc 8.
