### ISSUE TITLE
Base will not load

### ISSUE THREAD

**Issue by X-WildeModz-X** [ethylamine/PS4-RDR-2-Menu-Base#3]
Hi there 🤟
Thanks for the upload of the RDR2 base but there is a lot of issues that need to be attended to.
I to myself have tried to load your bin that came with the build and had no luck with getting it to load in the game or get any msg saying it loaded or detected game.
So I build my own base and used all of your address ( thanks again for sharing) with a lot of manipulation was able to get it to load with golden hen, detect 1.29 game version, setup environment, load into story then game crash.
Any help with this would be much appreciated or even if you could go back over your code to confirm that it’s correct input.
As I’m sure there is a few of us that would love to use this base you have shared with the modding community.

**Comment by ethylamine** [comment]
It's hard to say without at least knowing what firmware you are on.
The code as is works fine on my 5.05 .
If you're adding or changing things on your own code I can't possibly account for that.
How are you loading the payload?
Which version of HEN are you using (if at all)?
I just tested with goldHEN 2.0b on 5.05 and it worked fine.
Do not use goldHEN's bin loader as the payload won't work.
You have to load it normally via the web browser.

**Comment by X-WildeModz-X** [comment]
I am on 9.00 FW
I loaded the bin that came with your build via Mira and it crashed my console as soon as the bin was injected.

**Comment by ethylamine** [comment]
Try using goldHEN but load the payload via the web browser.

**Comment by X-WildeModz-X** [comment]
Tried that still won’t load
I don’t even get a msg that your base was loaded

**Comment by ethylamine** [comment]
You're going to need to look at kernel logs to determine what is happening.
Try using `printf_debug` throughout the code in `_main` and look at kernel logs. It could help pinpoint where in the code the payload is crashing.

**Comment by X-WildeModz-X** [comment]
There is a few different people trying to get this base you uploaded to work and we are all having the same problems.
It would be awesome if you could go back over your code and confirm that what you have uploaded to the modding community is actually a working base on 1.29.
Even a video of you injecting the menu and using it on 1.29 will confirm what you have shared actually works.
Considering this base is a port of 2much4u I’m sure he wouldn’t want his name on something that don’t work.

**Comment by ethylamine** [comment]
I had another tester try it out on 9.00 .
Worked without issue with goldHEN and the payload loaded via AlAzif's DNS host.
2much is cool he doesn't mind. The issue is something on your end.
I already suggested ways to debug it but seems you don't want to.
The code works fine for myself and those that have tested it.

**Comment by X-WildeModz-X** [comment]
I find it hard to believe the payload that comes with the base actually worked as I have had 3 different  FW try to load it and it don’t show that it’s injected or it crash console.
You first said it’s for all FW but now u can clearly see there is a problem with it as it won’t work on all
