### ISSUE TITLE
Crash on menu open

### ISSUE THREAD

**Issue by Nuii4** [ethylamine/PS4-RDR-2-Menu-Base#5]
Hi I'm on 9.00/1.29 the menu crashes the game when I try to open it. The precompiled version actually works fine for me but when I compile it using the sdk I get all the notifications up until the one that tells me the controls for the menu but It crashes my game when I try to open it ... I get no errors of any kind while compiling it, was just hoping someone could help steer me in the right direction

**Comment by ethylamine** [comment]
So I was just able to reproduce this issue using gcc 10.2.1 on my 5.05 ps4.
The precompiled payload on the repo right now was compiled with gcc 8.
What version of gcc are you running by any chance? 
This seems to not occur with gcc 8 as another user pointed out in a previous issue.
You can do `gcc --version` in your terminal to find out.

**Comment by Nuii4** [comment]
I was using gcc 9 switched to gcc 8 like you suggested and it works now with no issues thanks so much for the help
